# ~/.config/starship.toml

# Use custom format
format = """
[┌>](bold green)$username$hostname
[│](bold green)$directory$git_branch
[└─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# ~/.config/starship.toml

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

# ~/.config/starship.toml

[hostname]
ssh_only = false
format = "@[$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

# ~/.config/starship.toml

[git_branch]
format = "on [$branch]($style) "
